"""
SecureVault — Cloud Function handler for SCC Security Health Analytics alerts.

Receives Pub/Sub messages containing SCC findings, filters for high-severity
misconfigurations, and sends actionable email alerts via SendGrid/Brevo SMTP.
"""

import base64
import json
import os
from datetime import datetime, timezone

from cloudevents.http import CloudEvent
import functions_framework
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail


# Finding types we care about
MONITORED_FINDINGS = {
    "PUBLIC_BUCKET_ACL": {
        "severity": "CRITICAL",
        "description": "Cloud Storage bucket is publicly accessible",
        "remediation": "Remove allUsers and allAuthenticatedUsers from bucket IAM",
    },
    "OPEN_FIREWALL": {
        "severity": "HIGH",
        "description": "Firewall rule allows open ingress from the internet",
        "remediation": "Restrict source ranges to specific IPs or remove the rule",
    },
    "OVER_PRIVILEGED_SERVICE_ACCOUNT": {
        "severity": "HIGH",
        "description": "Service account has overly broad permissions",
        "remediation": "Replace primitive roles (roles/editor, roles/owner) with predefined custom roles",
    },
}


def parse_finding(cloud_event: CloudEvent) -> dict | None:
    """Extract and parse the SCC finding from a Pub/Sub CloudEvent."""
    try:
        message_data = json.loads(cloud_event.data["message"]["data"])
        finding = message_data.get("finding", {})

        category = finding.get("category", "")
        if category not in MONITORED_FINDINGS:
            return None

        return {
            "category": category,
            "severity": finding.get("severity", "UNKNOWN"),
            "resource": finding.get("resourceName", "unknown"),
            "recommendation": finding.get("sourceProperties", {}).get(
                "Recommendation", MONITORED_FINDINGS[category]["remediation"]
            ),
            "create_time": finding.get("createTime", datetime.now(timezone.utc).isoformat()),
        }
    except (KeyError, json.JSONDecodeError, base64.binascii.Error) as e:
        print(f"Failed to parse finding: {e}")
        return None


def format_alert_email(finding: dict) -> str:
    """Generate HTML email body for the finding alert."""
    template = MONITORED_FINDINGS.get(finding["category"], {})
    resource_name = finding["resource"].split("/")[-1] if "/" in finding["resource"] else finding["resource"]

    severity_color = "#d93025" if finding["severity"] == "CRITICAL" else "#f9ab00"

    return f"""
    <html>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #333;">
        <h2 style="color: #d93025;">Security Alert: {finding["category"]}</h2>
        <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
            <tr>
                <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Severity</td>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    <span style="background: {severity_color}; color: white; padding: 2px 8px; border-radius: 4px;">
                        {finding["severity"]}
                    </span>
                </td>
            </tr>
            <tr>
                <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Resource</td>
                <td style="padding: 8px; border: 1px solid #ddd; font-family: monospace;">{resource_name}</td>
            </tr>
            <tr>
                <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Description</td>
                <td style="padding: 8px; border: 1px solid #ddd;">{template.get("description", "N/A")}</td>
            </tr>
            <tr>
                <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Remediation</td>
                <td style="padding: 8px; border: 1px solid #ddd;">{finding["recommendation"]}</td>
            </tr>
            <tr>
                <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Detected At</td>
                <td style="padding: 8px; border: 1px solid #ddd;">{finding["create_time"]}</td>
            </tr>
        </table>
        <p style="margin-top: 20px; font-size: 12px; color: #666;">
            Alert generated by SecureVault —
            <a href="https://console.cloud.google.com/security/command-center/findings">View in SCC Console</a>
        </p>
    </body>
    </html>
    """


def send_alert_email(finding: dict) -> bool:
    """Send email alert via SendGrid/Brevo."""
    try:
        sg = SendGridAPIClient(os.environ["SENDGRID_API_KEY"])
        message = Mail(
            from_email=os.environ.get("ALERT_FROM_EMAIL", "security-alerts@securevault.dev"),
            to_emails=os.environ["ALERT_EMAIL"],
            subject=f"[SecureVault] {finding['severity']} — {finding['category']} detected",
            html_content=format_alert_email(finding),
        )
        response = sg.send(message)
        success = response.status_code == 202
        print(f"Email sent: {success} (status={response.status_code})")
        return success
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False


@functions_framework.cloud_event
def scc_alert_handler(cloud_event: CloudEvent) -> str:
    """Entry point: receives Pub/Sub CloudEvent, processes SCC finding, sends alert."""
    print(f"Received event: {cloud_event['type']}")

    finding = parse_finding(cloud_event)
    if not finding:
        return "Finding not in monitored set or parse error"

    print(f"Processing finding: {finding['category']} on {finding['resource']}")

    success = send_alert_email(finding)
    return f"Alert {'sent' if success else 'failed'} for {finding['category']}"
